# Generated by Django 4.1.3 on 2023-01-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=50, verbose_name='Nome de quem reivindicou *')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF *')),
                ('withdrawal_date', models.DateTimeField(verbose_name='Data de retirada')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Lost', max_length=9, verbose_name='Status')),
                ('name', models.CharField(max_length=20, verbose_name='Nome *')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('who_found', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome de quem encontrou *')),
                ('local_found', models.CharField(max_length=20, verbose_name='Local que foi encontrado *')),
                ('when_was_found', models.DateField(verbose_name='Data de quando foi encontrado *')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Foto')),
                ('shift', models.CharField(choices=[('Manhã', 'Matutino'), ('Tarde', 'Vespertino'), ('Noite', 'Noturno')], max_length=9, verbose_name='Turno')),
                ('withdrawal_deadline', models.DateField(verbose_name='Data limite para retirada *')),
                ('pickup_location', models.CharField(choices=[('Bloco Principal', 'Bloco Principal'), ('Bloco anexo', 'Bloco Anexo')], max_length=20, verbose_name='COADES *')),
                ('user_registration', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
