# Generated by Django 4.1.3 on 2022-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8, verbose_name='Status')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('who_found', models.CharField(max_length=50, verbose_name='Quem encontrou')),
                ('local_found', models.CharField(max_length=20, verbose_name='Local encontrado')),
                ('when_was_found', models.DateField(verbose_name='Data encontrado')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Foto')),
                ('shift', models.CharField(max_length=8, verbose_name='Turno')),
                ('withdrawal_deadline', models.DateField(verbose_name='Data limite para retirada')),
                ('pickup_location', models.CharField(max_length=20, verbose_name='Local para retirada')),
            ],
        ),
    ]
