# Generated by Django 4.1.3 on 2023-01-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='who_found',
            field=models.CharField(max_length=50, verbose_name='Nome de quem encontrou *'),
        ),
    ]
