# Generated by Django 4.1.3 on 2023-01-02 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=50, verbose_name='Nome de quem reivindicou *')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('withdrawal_date', models.DateTimeField(verbose_name='Data de retirada')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pickup_location',
            field=models.CharField(choices=[('Bloco Principal', 'Bloco Principal'), ('Bloco Anexo', 'Bloco Anexo')], max_length=20, verbose_name='COADES *'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shift',
            field=models.CharField(choices=[('', 'Selecione o turno'), ('Morning', 'Manhã'), ('Afternoon', 'Tarde'), ('Night', 'Noite')], max_length=9, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='Lost', max_length=9, verbose_name='Status'),
        ),
    ]
