# Generated by Django 4.1.3 on 2023-01-06 18:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_registration',
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, verbose_name=core.models.User),
        ),
    ]
