# Generated by Django 4.1.3 on 2023-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delivereditem_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
