# Generated by Django 4.1.3 on 2023-01-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_item_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimant',
            name='registration',
        ),
    ]
