# Generated by Django 4.1.3 on 2022-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
    ]
