# Generated by Django 4.1.3 on 2023-01-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
